# Site settings
author: Jacqueline Freeland
title: 
header-img: img/home-bg.png
email: secretartist272@gmail.com
copyright_name: Jacqueline Freeland
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: artistic_unique
github_username:  secretartist272

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
